### ISSUE TITLE
Gihub pages site returns a 404

### ISSUE THREAD

**Issue by harrisj** [propublica/schooner-tk#1]
https://propublica.github.io/schooner-tk  (sad trombone)

Push up the gh-pages branch. And thanks for making this awesome thing!

**Comment by thejefflarson** [comment]
lol I need to make a index.html will do v soon.

**Comment by thejefflarson** [comment]
there's an index now, i'm going to leave this open so i feel the weight of an unfinished project.

**Comment by harrisj** [comment]
Is an issue ever truly closed? Or do we carry it with us as an invisible but real spiritual burden for the rest of our days?

**Comment by thejefflarson** [comment]
you and i are connected by issues jake

**Comment by harrisj** [comment]
You can close this now I think.

**Comment by thejefflarson** [comment]
Oh right duh
