### ISSUE TITLE
library not found for -lippicv

### ISSUE THREAD

**Issue by oeon** [propublica/schooner-tk#10]
seems to be an opencv issue, but I just wanted to leave a note for anybody running into `library not found for -lippicv` when trying to make this. I removed the `-lippicv` flag from `opencv.pc` via https://github.com/kyamagu/mexopencv/issues/222#issuecomment-170984968 and was able to compile and install.

**Comment by thejefflarson** [comment]
Thanks! I'm not surprised, open cv has had a contentious relationship with
pkg-config in the past, I'll add a note to the docs.

**Comment by thejefflarson** [comment]
the makefile filters lippicv out now:

https://github.com/propublica/schooner-tk/blob/master/Makefile#L28

thanks!
