### ISSUE TITLE
Docs call for opencv3 but source files reference opencv2 headers

### ISSUE THREAD

**Issue by onyxfish** [propublica/schooner-tk#12]
Not clear what the intention is, but there seems to be a discrepancy?

**Comment by onyxfish** [comment]
Ah, I see, opencv3 installs heads under a folder called opencv2. That makes sense. Sigh. Now to figure out why it can't find the headers.

**Comment by thejefflarson** [comment]
opencv is kinda mess, lemme know if there's anything I can do to help....
