### ISSUE TITLE
schooner-cloud failing

### ISSUE THREAD

**Issue by jqtrde** [propublica/schooner-tk#4]
More questions... :smile: 

Build seem to work properly, and I was able to run `schooner-stitch` successfully. However, `schooner-cloud` is failing with the following:

```
/schooner-cloud ~/landsat/downloads/LC80110272014262LGN00/LC80110272014262LGN00_BQA.TIF qa.TIF
dyld: Library not loaded: /usr/local/lib/libopencv_calib3d.2.4.dylib
  Referenced from: /Users/j/code/schooner-tk/src/./schooner-cloud
  Reason: image not found
[1]    85242 trace trap  ./schooner-cloud  qa.TIF
```

Is that something you've seen before?

**Comment by jqtrde** [comment]
Seeing the same with `schooner-blend`.

Poked around, and rather than having a reference to:

```
libopencv_calib3d.2.4.dylib
```

I have:

```
libopencv_calib3d.3.0.dylib
libopencv_calib3d.dylib
```

Basically, it looks like schooner is looking for OpenCV 2.4, but Homebrew is installing 3.0.

**Comment by jqtrde** [comment]
Uninstalled both 2.4 and 3.0, and am rebuilding with 3.0.

**Comment by thejefflarson** [comment]
Did that end up working? I remember that open cv doesn't play very nicely
with pkg-config, but it does look like you were linking to a 2 series
library.

I think I should probably make a system where schooner downloads and links
to a local 3 install rather than a system one.

**Comment by jqtrde** [comment]
`blend` is working, haven't tried `cloud` yet, but I expect things should be working now.
