### ISSUE TITLE
Open-cv --devel argument throws error

### ISSUE THREAD

**Issue by petulla** [propublica/schooner-tk#7]
The open-csv install command throws the following error when trying to install:

`Error: No devel block is defined for homebrew/science/opencv`

**Comment by thejefflarson** [comment]
looks like homebrew made it it's own formula `opencv3` so I'll update the docs, i think `brew install homebrew/science/opencv3` will work for you.

**Comment by petulla** [comment]
Not sure if it's related, but upon trying to make the package:

`src/schooner-contrast.cc:4:10: fatal error:
      'opencv2/imgproc.hpp' file not found
#include <opencv2/imgproc.hpp>
         ^
1 error generated.
make: *** [src/schooner-contrast] Error 1`

**Comment by thejefflarson** [comment]
yeah you have basically 2 options either fiddle with CFLAGS and LDLIBS and PKG_CONFIG_PATH or run `brew link --force opencv3` which is the easier option but will break anything you have installed that relies on opencv

**Comment by petulla** [comment]
That did work, with unlinking opencv first.
