### ISSUE TITLE
Docs on schooner-blend

### ISSUE THREAD

**Issue by petulla** [propublica/schooner-tk#8]
Hi

This seems like a great library. Thanks for putting it together. I'm trying to understand how to use the blend routine. The example workflow provided shows what blend outputs look like, but only suggests that they are interesting. Indeed they are! I am wondering if there is more documentation on what the blended images can be used for to create cloudless imagery.

**Comment by thejefflarson** [comment]
Sorry for the late reply! Basically blending is useful as a way to remove
clouds, if you take 6 different Landsat scenes you can by pixel average out
the clouds.

One caveat that's not quite expressed in the blog post, is that the images
need to be both the same size and the same group coordinates, and that's
why the image came out all blurry in that post.

**Comment by thejefflarson** [comment]
You can see an example workflow with the gdal_translate commands here:

https://github.com/propublica/schooner-tk/issues/6#issuecomment-120476093
