### ISSUE TITLE
Make failing

### ISSUE THREAD

**Issue by mikejcorey** [propublica/schooner-tk#9]
This is on Ubuntu 14.04, with OpenCV 3.0.0, clang-3.3

clang++ -I/usr/include/gdal -g -std=c++11 -stdlib=libc++ -I/usr/local/include/opencv -I/usr/local/include   -I./src/    src/schooner-contrast.cc  -L/usr/lib -lgdal -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal   -std=c++11 -stdlib=libc++ -o src/schooner-contrast
/tmp/schooner-contrast-LMJKzW.o: In function `main':
/home/michaelcorey/opencv/opencv-3.0.0/build/schooner-tk/src/schooner-contrast.cc:46: undefined reference to`cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [src/schooner-contrast] Error 1

**Comment by thejefflarson** [comment]
I think that's still linking against your local install of opencv, is that version 3.0?

**Comment by thejefflarson** [comment]
you can change this line: https://github.com/propublica/schooner-tk/blob/master/Makefile#L16

to point to the right place where it is installed, but yeah I should make an actual build thing for this thing.

**Comment by mikejcorey** [comment]
Hi Jeff: Thanks for responding. I am a little out of my depth in changing Makefiles and in using OpenCV. How would I specify a specific path on that line? And would I point it at a file or a directory?

For example, I found files here:

/usr/local/bin/opencv_annotation

But I'm not sure what method I'm targetting, or if I'm even on the right track.

Thanks again.

**Comment by oeon** [comment]
I'm also getting an error like @mikejcorey while attempting to install on Ubuntu.

**Comment by esagara** [comment]
So I have also been trying to install on Ubuntu and have been running into the same issue. I am fairly certain I removed all previous versions of OpenCV.

```
$ pkg-config --modversion opencv
3.0.0
```

When running make on Schooner-TK:

```
clang++ -I/usr/include/gdal -g -std=c++11 -stdlib=libc++ -I/usr/local/include/opencv -I/usr/local/include  -I./src/    src/schooner-multibalance.cc  -L/usr/lib -lgdal -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal  -std=c++11 -stdlib=libc++ -o src/schooner-multibalance
/tmp/schooner-multibalance-3c5046.o: In function `main':
/home/esagara/schooner-tk/src/schooner-multibalance.cc:26: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<builtin>: recipe for target 'src/schooner-multibalance' failed
make: *** [src/schooner-multibalance] Error 1
```

**Comment by thejefflarson** [comment]
does it work if you run this command?

clang++ -I/usr/include/gdal -g -std=c++11 -stdlib=libc++ -I/usr/local/include/opencv -I/usr/local/include  -I./src/    src/schooner-multibalance.cc  -L/usr/lib -lgdal -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal -o src/schooner-multibalance

**Comment by esagara** [comment]
No it still throws the same error.

**Comment by esagara** [comment]
If it helps here is the command run with verbose output:

```
$ clang++ -v -I/usr/include/gdal -g -std=c++11 -stdlib=libc++ -I/usr/local/include/opencv -I/usr/local/include -I./src/ src/schooner-multibalance.cc -L/usr/lib -lgdal -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal -o src/schooner-multibalance
Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.0.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.0.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.0.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.0.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-3.6/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name schooner-multibalance.cc -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.25 -v -g -dwarf-column-info -resource-dir /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0 -I /usr/include/gdal -I /usr/local/include/opencv -I /usr/local/include -I ./src/ -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/esagara/schooner-tk -ferror-limit 19 -fmessage-length 160 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/schooner-multibalance-ebc95f.o -x c++ src/schooner-multibalance.cc
clang -cc1 version 3.6.0 based upon LLVM 3.6.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/gdal
 /usr/local/include/opencv
 ./src
 /usr/include/c++/v1
 /usr/local/include
 /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o src/schooner-multibalance /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/crtbegin.o -L/usr/lib -L/usr/local/lib -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../.. -L/usr/lib/llvm-3.6/bin/../lib -L/lib -L/usr/lib /tmp/schooner-multibalance-ebc95f.o -lgdal -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal -lc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crtn.o
/tmp/schooner-multibalance-ebc95f.o: In function `main':
/home/esagara/schooner-tk/src/schooner-multibalance.cc:26: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by esagara** [comment]
Ok so I have not tested the install yet, but editing the make file seems to have allowed it to go through. In short what I did was switch clang++ to g++ and removed the -stdlib flags. Is this a bad idea?

```
CC = g++
CXX = g++
RONN = $(wildcard man/*.ronn)
HTML = $(RONN:.ronn=.html)

SRCS = $(wildcard src/*.cc)
BINS = $(basename $(SRCS))

all: doc binaries $(HTML)
doc: $(HTML)
binaries: $(BINS)

man/%.html: man/%.ronn
    ronn --manual=schooner-tk --organization=propublica $<

CXXFLAGS = $(shell gdal-config --cflags) -g -std=c++11 $(shell pkg-config --cflags opencv) -I./src/
LDLIBS = $(shell gdal-config --libs) $(shell pkg-config --libs opencv) -std=c++11

clean:
    rm man/*.html man/*.1 $(BINS)

install: all
    install $(BINS) /usr/local/bin
    install man/*.1 /usr/local/share/man/man1/

.PHONY: all clean doc binaries install
```

**Comment by thejefflarson** [comment]
Might be for us os x users but I'll give it a go tomorrow.

**Comment by thejefflarson** [comment]
Ok, can you pull and try now?

**Comment by mikejcorey** [comment]
Well, I get a new and different error. I also didn't uninstall anything before trying this (I tried Eric's manual solution yesterday), so that could be interfering as well.

Full output below:

g++ -g -std=c++11 -I./src/ -I/usr/include/gdal -L/usr/lib -lgdal -I/usr/local/include/opencv -I/usr/local/include  -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal      src/schooner-blend.cc   -o src/schooner-blend
/tmp/cc577xwk.o: In function `operator*=':
/usr/local/include/opencv2/core/operations.hpp:254: undefined reference to`cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
/tmp/cc577xwk.o: In function `balance(std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)':
/home/michaelcorey/schooner-tk/src/utils.h:21: undefined reference to`cv::split(cv::_InputArray const&, cv::_OutputArray const&)'
/home/michaelcorey/schooner-tk/src/utils.h:25: undefined reference to `cv::Mat::reshape(int, int) const'
/home/michaelcorey/schooner-tk/src/utils.h:25: undefined reference to`cv::Mat::reshape(int, int) const'
/home/michaelcorey/schooner-tk/src/utils.h:26: undefined reference to `cv::Mat::reshape(int, int) const'
/home/michaelcorey/schooner-tk/src/utils.h:26: undefined reference to`cv::Mat::copyTo(cv::_OutputArray const&) const'
/home/michaelcorey/schooner-tk/src/utils.h:27: undefined reference to `cv::sort(cv::_InputArray const&, cv::_OutputArray const&, int)'
/home/michaelcorey/schooner-tk/src/utils.h:56: undefined reference to`cv::split(cv::_InputArray const&, cv::_OutputArray const&)'
/home/michaelcorey/schooner-tk/src/utils.h:60: undefined reference to `cv::operator-(cv::Mat const&, cv::Scalar_<double> const&)'
/home/michaelcorey/schooner-tk/src/utils.h:60: undefined reference to `cv::operator/(cv::MatExpr const&, double)'
/home/michaelcorey/schooner-tk/src/utils.h:60: undefined reference to`cv::operator_(cv::MatExpr const&, double)'
/home/michaelcorey/schooner-tk/src/utils.h:64: undefined reference to `cv::merge(cv::_InputArray const&, cv::_OutputArray const&)'
/tmp/cc577xwk.o: In function`get_image(char_)':
/home/michaelcorey/schooner-tk/src/utils.h:70: undefined reference to `cv::imread(cv::String const&, int)'
/home/michaelcorey/schooner-tk/src/utils.h:95: undefined reference to`cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
/tmp/cc577xwk.o: In function `assign_projection(void*, void*)':
/home/michaelcorey/schooner-tk/src/utils.h:103: undefined reference to`GDALGetGeoTransform'
/home/michaelcorey/schooner-tk/src/utils.h:104: undefined reference to `GDALSetGeoTransform'
/home/michaelcorey/schooner-tk/src/utils.h:106: undefined reference to`GDALGetProjectionRef'
/home/michaelcorey/schooner-tk/src/utils.h:107: undefined reference to `GDALGetProjectionRef'
/home/michaelcorey/schooner-tk/src/utils.h:107: undefined reference to`GDALSetProjection'
/tmp/cc577xwk.o: In function `close_datasets(void**, int)':
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:16: undefined reference to`GDALClose'
/tmp/cc577xwk.o: In function `open_datasets(void**, int, char**)':
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:24: undefined reference to`GDALGetRasterCount'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:24: undefined reference to `GDALGetRasterXSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:24: undefined reference to`GDALGetRasterYSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:26: undefined reference to `GDALOpen'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:27: undefined reference to`CPLGetLastErrorMsg'
/tmp/cc577xwk.o: In function `process_datasets(void*, void**, int)':
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:60: undefined reference to`GDALGetRasterCount'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:61: undefined reference to `GDALGetRasterXSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:62: undefined reference to`GDALGetRasterYSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:74: undefined reference to `GDALGetRasterBand'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:76: undefined reference to`GDALRasterIO'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:118: undefined reference to `GDALGetRasterBand'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:120: undefined reference to`GDALRasterIO'
/tmp/cc577xwk.o: In function `main':
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:135: undefined reference to`GDALAllRegister'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:147: undefined reference to `CSLSetNameValue'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:152: undefined reference to`GDALGetRasterCount'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:152: undefined reference to `GDALGetRasterYSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:152: undefined reference to`GDALGetRasterXSize'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:152: undefined reference to `GDALGetDriverByName'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:152: undefined reference to`GDALCreate'
/home/michaelcorey/schooner-tk/src/schooner-blend.cc:161: undefined reference to `GDALClose'
/tmp/cc577xwk.o: In function`cv::String::String(char const_)':
/usr/local/include/opencv2/core/cvstd.hpp:618: undefined reference to `cv::String::allocate(unsigned long)'
/tmp/cc577xwk.o: In function`cv::String::~String()':
/usr/local/include/opencv2/core/cvstd.hpp:660: undefined reference to `cv::String::deallocate()'
/tmp/cc577xwk.o: In function`cv::Mat::Mat(cv::Mat const&)':
/usr/local/include/opencv2/core/mat.inl.hpp:389: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/tmp/cc577xwk.o: In function`cv::Mat::~Mat()':
/usr/local/include/opencv2/core/mat.inl.hpp:556: undefined reference to `cv::fastFree(void_)'
/tmp/cc577xwk.o: In function `cv::Mat::create(int, int, int)':
/usr/local/include/opencv2/core/mat.inl.hpp:648: undefined reference to`cv::Mat::create(int, int const_, int)'
/tmp/cc577xwk.o: In function `cv::Mat::release()':
/usr/local/include/opencv2/core/mat.inl.hpp:667: undefined reference to`cv::Mat::deallocate()'
collect2: error: ld returned 1 exit status
make: *_\* [src/schooner-blend] Error 1

**Comment by esagara** [comment]
I am guessing there is an ordering issue at [https://github.com/propublica/schooner-tk/blob/master/Makefile#L27](). I'll play around for a second and see if I can get it to work.

**Comment by mikejcorey** [comment]
Merged branch works for me.

**Comment by oeon** [comment]
me too :+1:

**Comment by thejefflarson** [comment]
sweet sorry it took so long guys.
